//! WLADX-format symbol map file generation
//!
//! Generates `.sym` files compatible with Mega Drive emulators
//! (BlastEm, Gens KMod, etc.) for source-level debugging.

use std::collections::HashMap;
use std::fmt::Write;

/// Generate a WLADX-format `.sym` file from the assembler's symbol table.
///
/// The output format is:
/// ```text
/// ; Symbol map generated by smdc
/// [labels]
/// 00:000200 main
/// 00:FF8000 player_x
/// ```
///
/// Internal labels (`.L*`, `.sdk_*`, `__data_*`, `__sdk_*`) are filtered out.
/// Labels are sorted by address.
pub fn generate_sym_file(symbols: &HashMap<String, u32>) -> String {
    let mut output = String::new();
    output.push_str("; Symbol map generated by smdc\n");
    output.push_str("[labels]\n");

    let mut sorted: Vec<_> = symbols
        .iter()
        .filter(|(name, _)| !is_internal_label(name))
        .collect();
    sorted.sort_by_key(|(_, addr)| *addr);

    for (name, addr) in sorted {
        let _ = writeln!(output, "00:{addr:06X} {name}");
    }

    output
}

/// Parse a WLADX-format `.sym` file back into a symbol table.
///
/// Accepts the format produced by [`generate_sym_file`]: comment lines
/// (`;`), section headers (`[labels]`), and `BB:AAAAAA name` entries.
/// Unparseable lines are skipped.
pub fn parse_sym_file(content: &str) -> HashMap<String, u32> {
    let mut symbols = HashMap::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with(';') || line.starts_with('[') {
            continue;
        }
        let mut parts = line.split_whitespace();
        let (Some(addr_str), Some(name)) = (parts.next(), parts.next()) else {
            continue;
        };
        // Strip the bank prefix ("00:000200" -> "000200")
        let addr_str = addr_str.rsplit(':').next().unwrap_or(addr_str);
        if let Ok(addr) = u32::from_str_radix(addr_str, 16) {
            symbols.insert(name.to_string(), addr);
        }
    }
    symbols
}

fn is_internal_label(name: &str) -> bool {
    // All labels starting with '.' are compiler-internal
    name.starts_with('.') || name.starts_with("__data_") || name.starts_with("__sdk_")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sym_file_empty_symbols() {
        let symbols = HashMap::new();
        let output = generate_sym_file(&symbols);
        assert_eq!(output, "; Symbol map generated by smdc\n[labels]\n");
    }

    #[test]
    fn sym_file_sorted_by_address() {
        let mut symbols = HashMap::new();
        symbols.insert("vdp_init".to_string(), 0x000280u32);
        symbols.insert("main".to_string(), 0x000240u32);
        symbols.insert("_start".to_string(), 0x000200u32);

        let output = generate_sym_file(&symbols);
        let lines: Vec<&str> = output.lines().collect();
        assert_eq!(lines[2], "00:000200 _start");
        assert_eq!(lines[3], "00:000240 main");
        assert_eq!(lines[4], "00:000280 vdp_init");
    }

    #[test]
    fn sym_file_filters_internal_labels() {
        let mut symbols = HashMap::new();
        symbols.insert("main".to_string(), 0x000200u32);
        symbols.insert(".Lif_0".to_string(), 0x000210u32);
        symbols.insert(".sdk_vwvs_not_0".to_string(), 0x000220u32);
        symbols.insert("__data_rom_start".to_string(), 0x000300u32);
        symbols.insert("__sdk_frame_count".to_string(), 0xFF8000u32);
        symbols.insert("player_x".to_string(), 0xFF8004u32);

        let output = generate_sym_file(&symbols);
        assert!(output.contains("main"));
        assert!(output.contains("player_x"));
        assert!(!output.contains(".Lif_0"));
        assert!(!output.contains(".sdk_"));
        assert!(!output.contains("__data_"));
        assert!(!output.contains("__sdk_"));
    }

    #[test]
    fn sym_file_ram_addresses() {
        let mut symbols = HashMap::new();
        symbols.insert("score".to_string(), 0xFF8000u32);

        let output = generate_sym_file(&symbols);
        assert!(output.contains("00:FF8000 score"));
    }

    #[test]
    fn sym_file_roundtrip() {
        let mut symbols = HashMap::new();
        symbols.insert("main".to_string(), 0x000200u32);
        symbols.insert("player_x".to_string(), 0xFF8000u32);

        let parsed = parse_sym_file(&generate_sym_file(&symbols));
        assert_eq!(parsed, symbols);
    }

    #[test]
    fn parse_sym_skips_garbage_lines() {
        let content = "; comment\n[labels]\nnot-an-entry\nZZ main\n00:000200 main\n";
        let parsed = parse_sym_file(content);
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed["main"], 0x200);
    }

    #[test]
    fn sym_file_wladx_format() {
        let mut symbols = HashMap::new();
        symbols.insert("main".to_string(), 0x000200u32);

        let output = generate_sym_file(&symbols);
        assert!(output.starts_with("; Symbol map generated by smdc\n[labels]\n"));
        assert!(output.contains("00:000200 main\n"));
    }
}
